-- AI 评审团相关表。
-- ai_score_report 仍然是本场得分（主评分）；评审团只使用同一份原始证据快照，
-- 不把官方报告分数或结论作为评审输入。

CREATE TABLE IF NOT EXISTS `ai_judge_persona` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(16) NOT NULL COMMENT '评委画像编码，如 ISTJ',
  `name` VARCHAR(64) NOT NULL COMMENT '评委画像名称',
  `short_label` VARCHAR(128) DEFAULT NULL COMMENT '评委关注点短标签',
  `focus_dimensions_json` TEXT COMMENT '重点关注的评分维度JSON',
  `judge_profile_json` MEDIUMTEXT COMMENT '详细评委人格画像JSON',
  `rubric_focus_json` TEXT COMMENT '重点评分维度与观测项JSON',
  `scoring_bias_json` TEXT COMMENT '关注偏好JSON，仅影响观察角度，不改变统一评分规则',
  `prompt_modifier` TEXT COMMENT '该评委独立评审时的提示词补充',
  `description` TEXT COMMENT '评委画像说明',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_judge_persona_code` (`code`),
  KEY `idx_ai_judge_persona_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI评委画像定义表';

CREATE TABLE IF NOT EXISTS `ai_jury_session` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `meeting_id` BIGINT DEFAULT NULL COMMENT '会议ID',
  `scoring_session_id` BIGINT DEFAULT NULL COMMENT 'AI评分会话ID',
  `base_report_id` BIGINT DEFAULT NULL COMMENT '本场得分报告ID，仅用于对比展示',
  `seed` VARCHAR(64) NOT NULL COMMENT '稳定抽取评委画像的随机种子',
  `standard_version` VARCHAR(64) DEFAULT NULL,
  `persona_pool_version` VARCHAR(64) DEFAULT NULL,
  `judge_count` INT NOT NULL DEFAULT 9,
  `status` VARCHAR(32) NOT NULL DEFAULT 'processing' COMMENT '状态：processing/completed/partial_failed/failed',
  `official_score` DECIMAL(5,2) DEFAULT NULL COMMENT '本场得分，仅用于展示对比',
  `jury_trimmed_avg` DECIMAL(5,2) DEFAULT NULL COMMENT '去掉1个最高分和1个最低分后的平均分',
  `jury_raw_avg` DECIMAL(5,2) DEFAULT NULL COMMENT '成功评委报告的原始平均分',
  `highest_score` DECIMAL(5,2) DEFAULT NULL,
  `lowest_score` DECIMAL(5,2) DEFAULT NULL,
  `score_diff_from_official` DECIMAL(6,2) DEFAULT NULL COMMENT '评审团去极值均分减本场得分',
  `evidence_snapshot_path` VARCHAR(500) DEFAULT NULL COMMENT '9位评委共同使用的证据快照路径',
  `result_path` VARCHAR(500) DEFAULT NULL COMMENT '评审团汇总结果路径',
  `error_message` TEXT,
  `started_at` DATETIME DEFAULT NULL,
  `completed_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_jury_session_meeting_status` (`meeting_id`, `status`),
  KEY `idx_jury_session_scoring_session_status` (`scoring_session_id`, `status`),
  KEY `idx_jury_session_created_at` (`created_at`),
  KEY `idx_jury_session_base_report` (`base_report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI评审团评审会话表';

CREATE TABLE IF NOT EXISTS `ai_jury_member` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `jury_session_id` BIGINT NOT NULL,
  `persona_id` BIGINT NOT NULL,
  `persona_code` VARCHAR(16) NOT NULL,
  `seat_no` INT NOT NULL COMMENT '评委席位号，1-9',
  `display_name` VARCHAR(64) DEFAULT NULL,
  `role_label` VARCHAR(128) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_jury_member_seat` (`jury_session_id`, `seat_no`),
  UNIQUE KEY `uk_jury_member_persona` (`jury_session_id`, `persona_code`),
  KEY `idx_jury_member_jury` (`jury_session_id`),
  KEY `idx_jury_member_persona` (`persona_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI评审团成员席位表';

CREATE TABLE IF NOT EXISTS `ai_judge_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `jury_session_id` BIGINT NOT NULL,
  `member_id` BIGINT NOT NULL,
  `meeting_id` BIGINT DEFAULT NULL,
  `scoring_session_id` BIGINT DEFAULT NULL COMMENT 'AI评分会话ID',
  `persona_code` VARCHAR(16) NOT NULL,
  `overall_score` DECIMAL(5,2) DEFAULT NULL,
  `dimensions_json` MEDIUMTEXT,
  `highlights_json` TEXT,
  `critical_issues_json` TEXT,
  `improvement_priorities_json` TEXT,
  `evidence_summary_json` TEXT,
  `persona_view_json` TEXT,
  `report_json` MEDIUMTEXT,
  `model` VARCHAR(100) DEFAULT NULL,
  `provider` VARCHAR(50) DEFAULT NULL,
  `tokens_json` TEXT,
  `status` VARCHAR(32) NOT NULL DEFAULT 'processing',
  `error_message` TEXT,
  `started_at` DATETIME DEFAULT NULL,
  `completed_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_judge_report_member` (`jury_session_id`, `member_id`),
  KEY `idx_judge_report_jury_status` (`jury_session_id`, `status`),
  KEY `idx_judge_report_meeting` (`meeting_id`),
  KEY `idx_judge_report_scoring_session` (`scoring_session_id`),
  KEY `idx_judge_report_persona` (`persona_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI单评委评审报告表';

CREATE TABLE IF NOT EXISTS `ai_jury_aggregate` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `jury_session_id` BIGINT NOT NULL,
  `meeting_id` BIGINT DEFAULT NULL,
  `scoring_session_id` BIGINT DEFAULT NULL COMMENT 'AI评分会话ID',
  `official_score` DECIMAL(5,2) DEFAULT NULL,
  `raw_average_score` DECIMAL(5,2) DEFAULT NULL,
  `trimmed_average_score` DECIMAL(5,2) DEFAULT NULL,
  `trimmed_total_score` DECIMAL(6,2) DEFAULT NULL COMMENT '去掉最高最低后的计分总分',
  `trimmed_count` INT DEFAULT NULL COMMENT '去掉最高最低后的计分评委数',
  `removed_high_report_id` BIGINT DEFAULT NULL,
  `removed_low_report_id` BIGINT DEFAULT NULL,
  `score_stats_json` TEXT,
  `dimension_disagreement_json` TEXT,
  `consensus_issues_json` TEXT,
  `persona_insights_json` TEXT,
  `optimization_suggestions_json` MEDIUMTEXT,
  `aggregate_report_json` MEDIUMTEXT,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_jury_aggregate_session` (`jury_session_id`),
  KEY `idx_jury_aggregate_meeting` (`meeting_id`),
  KEY `idx_jury_aggregate_scoring_session` (`scoring_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI评审团汇总与分歧分析表';
