import math

import pytest

from app.services.media_evidence.three_d_speaker_contract import (
    ThreeDSpeakerContractError,
    normalize_three_d_speaker_result,
    parse_rttm,
)


def test_parses_rttm_and_coalesces_adjacent_turns_from_the_same_joint_cluster():
    turns = parse_rttm(
        "\n".join(
            [
                "# generated by 3D-Speaker",
                "SPEAKER meeting 0 2.000 1.000 <NA> <NA> 7 <NA> <NA>",
                "SPEAKER meeting 0 0.500 1.500 <NA> <NA> 7 <NA> <NA>",
                "SPEAKER meeting 0 3.100 0.400 <NA> <NA> 2 <NA> <NA>",
            ]
        ),
        duration_ms=4000,
    )

    assert turns == [
        {
            "turnId": "3DSPK_TURN_1",
            "startMs": 500,
            "endMs": 3000,
            "rawSpeakerId": "3DSPK_7",
            "sourceClusterId": "3DSPK_7",
            "speakerVerification": "JOINT_AUDIO_VISUAL",
        },
        {
            "turnId": "3DSPK_TURN_2",
            "startMs": 3100,
            "endMs": 3500,
            "rawSpeakerId": "3DSPK_2",
            "sourceClusterId": "3DSPK_2",
            "speakerVerification": "JOINT_AUDIO_VISUAL",
        },
    ]


@pytest.mark.parametrize(
    "line,code",
    [
        ("SPEAKER meeting 0 -1 2 <NA> <NA> 1 <NA> <NA>", "invalid_time"),
        ("SPEAKER meeting 0 nan 2 <NA> <NA> 1 <NA> <NA>", "invalid_time"),
        ("SPEAKER meeting 0 3 2 <NA> <NA> 1 <NA> <NA>", "out_of_bounds"),
        ("SPEAKER meeting 0 0 1 <NA> <NA> ../../x <NA> <NA>", "invalid_speaker"),
        ("LEXEME meeting 0 0 1 <NA> <NA> 1 <NA> <NA>", "invalid_record"),
    ],
)
def test_rejects_unsafe_or_out_of_bounds_rttm(line, code):
    with pytest.raises(ThreeDSpeakerContractError, match=code):
        parse_rttm(line, duration_ms=4000)


def test_empty_rttm_is_explicitly_incomplete_without_inventing_a_person():
    result = normalize_three_d_speaker_result(
        {
            "contractVersion": "3d-speaker-local-v1",
            "status": "completed",
            "provider": "local_3d_speaker",
            "turns": [],
            "diagnostics": {"processingDurationMs": 10, "peakRssBytes": 100},
        },
        duration_ms=4000,
    )

    assert result["status"] == "evidence_incomplete"
    assert result["turns"] == []
    assert result["diagnostics"]["speakerClusterCount"] == 0


def test_normalizer_does_not_fabricate_confidence_and_derives_safe_diagnostics():
    result = normalize_three_d_speaker_result(
        {
            "contractVersion": "3d-speaker-local-v1",
            "status": "completed",
            "provider": "local_3d_speaker",
            "turns": [
                {
                    "turnId": "3DSPK_TURN_1",
                    "startMs": 100,
                    "endMs": 1100,
                    "rawSpeakerId": "3DSPK_A",
                    "sourceClusterId": "3DSPK_A",
                    "speakerVerification": "JOINT_AUDIO_VISUAL",
                }
            ],
            "diagnostics": {"processingDurationMs": 10, "peakRssBytes": 100},
        },
        duration_ms=4000,
    )

    assert "confidence" not in result["turns"][0]
    assert result["diagnostics"]["speakerClusterCount"] == 1
    assert result["diagnostics"]["turnCount"] == 1
    assert result["diagnostics"]["speechDurationMs"] == 1000


def test_normalizer_rejects_score_fields_at_any_depth():
    with pytest.raises(ThreeDSpeakerContractError, match="forbidden_score_field"):
        normalize_three_d_speaker_result(
            {
                "contractVersion": "3d-speaker-local-v1",
                "status": "completed",
                "provider": "local_3d_speaker",
                "turns": [],
                "diagnostics": {"overallScore": 88},
            },
            duration_ms=4000,
        )
