-- AI 评分报告表
CREATE TABLE IF NOT EXISTS `ai_score_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `session_id` BIGINT DEFAULT NULL COMMENT 'AI评分会话ID',
  `meeting_id` BIGINT DEFAULT NULL COMMENT '关联会议ID，上传视频评分可为空',
  `overall_score` DECIMAL(5,2) DEFAULT NULL COMMENT 'AI总分（百分制）',
  `dimensions_json` TEXT COMMENT '维度得分 JSON',
  `highlights_json` TEXT COMMENT '亮点 JSON 数组',
  `critical_issues_json` TEXT COMMENT '问题 JSON 数组',
  `improvement_priorities_json` TEXT COMMENT '改进建议 JSON 数组',
  `action_plan_json` LONGTEXT COMMENT '可执行行动计划 JSON 数组',
  `score_projection_json` LONGTEXT COMMENT '全部整改验收后的规则情景预测 JSON',
  `transcript` LONGTEXT COMMENT 'ASR 转录文本',
  `speech_quality_json` TEXT COMMENT '语音质量分析 JSON',
  `score_calibration_json` TEXT COMMENT '技术与现场演示校准 JSON',
  `rule_engine_version` VARCHAR(64) DEFAULT NULL COMMENT '规则引擎版本',
  `structured_result_json` TEXT COMMENT '规则引擎结构化结果 JSON',
  `current_score_cap` DECIMAL(6,2) DEFAULT NULL COMMENT '本轮证据上限',
  `recovered_score` DECIMAL(6,2) DEFAULT NULL COMMENT '本轮追回分',
  `model` VARCHAR(50) DEFAULT NULL COMMENT '使用的AI模型',
  `result_path` VARCHAR(500) DEFAULT NULL COMMENT 'AI服务结果文件路径',
  `status` VARCHAR(20) NOT NULL DEFAULT 'processing' COMMENT '状态: processing/completed/failed',
  `error_message` TEXT COMMENT '错误信息',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始分析时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session` (`session_id`),
  UNIQUE KEY `uk_meeting` (`meeting_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI评分报告';
